<?xml version="1.0" encoding="utf-8"?><Database Name="DB_121619_webadel" EntityNamespace="Webadel7.DB_Badges" ContextNamespace="Webadel7.DB_Badges" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:s15.winhost.com;Initial Catalog=DB_121619_webadel;Integrated Security=False;User ID=DB_121619_webadel_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Webadel" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Badge_User" Member="Badge_Users">
    <Type Name="Badge_User">
      <Column Name="userId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="badgeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="awarded" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="new" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Badge_User" Member="User" ThisKey="userId" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Badge_Badge_User" Member="Badge" ThisKey="badgeId" OtherKey="id" Type="Badge" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="trusted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="aide" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cosysop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="attachmentDisplay" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="enableSwipe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="enablePredictiveText" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="lastActivity" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="twit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="miscDictionary" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Association Name="User_Badge_User" Member="Badge_Users" ThisKey="id" OtherKey="userId" Type="Badge_User" />
      <Association Name="User_Badge" Member="Badges" ThisKey="id" OtherKey="creator" Type="Badge" />
    </Type>
  </Table>
  <Table Name="dbo.Badge" Member="Badges">
    <Type Name="Badge">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Column Name="added" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="creator" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="pendingApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="assignmentTypes" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Badge_Badge_User" Member="Badge_Users" ThisKey="id" OtherKey="badgeId" Type="Badge_User" />
      <Association Name="User_Badge" Member="User" ThisKey="creator" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>